# Generated by Django 4.2 on 2023-04-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='time_limit',
            field=models.IntegerField(default=0),
        ),
    ]
